### ISSUE TITLE
Captains UNiform jacket invisible

### ISSUE THREAD

**Issue by Warbidon** [EscapePodNo5/EPN5-Neb#41]
#### Description of issue
https://i.imgur.com/a5RgEmm.png
Captains jacket is invisible. in icon. I didnt try putting it on out of risk of bugging myself.

#### Difference between expected and actual behavior

Captains jacket should have an idon in hand.

#### Steps to reproduce
spawn captains jacket, boggle.

#### Specific information for locating

captain's uniform jacket

#### Client version, Server revision & Game ID
Client Version: 513
Server Revision: ea3ab0ebea8b03301619f4d45736600d8d61b48d - dev - 2020-11-10
Game ID: b94-aFMT
Current map: USN Odyssey

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by Mazianni** [comment]
Nebula issue; send to them.
