### ISSUE TITLE
Brig cell timers incorrect text wrapping

### ISSUE THREAD

**Issue by Allfd** [EscapePodNo5/EPN5-Neb#42]
![image](https://user-images.githubusercontent.com/8165455/98624985-d95f8f00-22dc-11eb-8f5a-4a3e1e6dc1f7.png)

#### Description of issue
The brig cell timers text may expand over the display and onto the tile behind them.

#### Steps to reproduce

Set a time on the brig cell timer

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by Mazianni** [comment]
Will see about a workaround for this.

**Comment by Mazianni** [comment]
resolved
