### ISSUE TITLE
Bug - Security cells & Timers

### ISSUE THREAD

**Issue by Stutternov** [EscapePodNo5/EPN5-Neb#43]
### Description of issue

- Using security HUD keeps giving a 'timer for X cell has expired' every five seconds.

![image](https://user-images.githubusercontent.com/47883419/98625211-2cd1dd00-22dd-11eb-8765-30958bb23c24.png)

#### Difference between expected and actual behavior

Spam!!!!!

#### Steps to reproduce

Be Shitcurity, wear glasses

#### Length of time in which bug has been known to occur

Yes

#### Client version, Server revision & Game ID

 Client Version: 513
Server Revision: ea3ab0ebea8b03301619f4d45736600d8d61b48d - dev - 2020-11-10
Game ID: b94-aFMT

#### Issue bingo

- [x ] Issue could be reproduced at least once
- [ x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by Mazianni** [comment]
resolved
