### ISSUE TITLE
Bug - PDA Crash & Will Not Re-Open

### ISSUE THREAD

**Issue by Stutternov** [EscapePodNo5/EPN5-Neb#44]
#### Description of issue

Upon opening ones PDA and trying to access the crew manifest the window will close and you will no longer be able to open your PDA

#### Difference between expected and actual behavior

Uhhh let me use my PDA

#### Steps to reproduce

Open PDa. Click crew manifest.

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: ea3ab0ebea8b03301619f4d45736600d8d61b48d - dev - 2020-11-10
Game ID: b94-aFMT

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by Mazianni** [comment]
resolved
