### ISSUE TITLE
Armory - Map Issue

### ISSUE THREAD

**Issue by Stutternov** [EscapePodNo5/EPN5-Neb#45]
#### Description of issue

Instead of Windoors in front of the display racks it is normal glass windows

#### Difference between expected and actual behavior

I'm assuming this was not intentional.

#### Steps to reproduce

Break glass in case of emergency

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by Mazianni** [comment]
This is intentional.
