### ISSUE TITLE
Engine room access

### ISSUE THREAD

**Issue by Allfd** [EscapePodNo5/EPN5-Neb#46]
## Description of issue

It is possible to gain access to the engine room via primary power storage, while not possible through the engine room doors.

#### Difference between expected and actual behavior

I am not sure, either you should have access to the engine or not?

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by Mazianni** [comment]
resolved
