### ISSUE TITLE
Volume limit always reads as 0% on engines.

### ISSUE THREAD

**Issue by Allfd** [EscapePodNo5/EPN5-Neb#47]
#### Description of issue

No matter what is set, the volume limit on the engine panel will always read as 0%

#### Difference between expected and actual behavior

It should indicated different things at different power settings.

![image](https://user-images.githubusercontent.com/8165455/98626358-8e934680-22df-11eb-9f2c-265a8c09ea85.png)

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by Mazianni** [comment]
Nebula issue; send upstream.
