### ISSUE TITLE
Automatic stop direction control is non-functional

### ISSUE THREAD

**Issue by Allfd** [EscapePodNo5/EPN5-Neb#48]
#### Description of issue

The X on the helm control will not actually stop the ship, opposite thrust must be applied manually.

![image](https://user-images.githubusercontent.com/8165455/98626448-ce5a2e00-22df-11eb-9df5-38d04d870542.png)

#### Difference between expected and actual behavior

It is expected that this button will stop the ship

#### Steps to reproduce

Move ship in a direction, use button to stop movement.

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by Mazianni** [comment]
*Probably* a Nebula issue. Send upstream.
