### ISSUE TITLE
Taser bolt sticks around after you neck grab shoot a guy multiple times in the head.

### ISSUE THREAD

**Issue by Warbidon** [EscapePodNo5/EPN5-Neb#49]
#### Description of issue
https://i.imgur.com/Fhj8XDw.png

#### Difference between expected and actual behavior
tasers bolts should go away

#### Steps to reproduce
point blanka  guy in the head witha neck grabbed taser bruh

#### Specific information for locating

energy gun in captains locker.

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by Mazianni** [comment]
Nebula issue; send to them.
