### ISSUE TITLE
Bug  Skrell are not playable

### ISSUE THREAD

**Issue by Warbidon** [EscapePodNo5/EPN5-Neb#50]
#### Description of issue

cannot join as a skrell from character screen/ make skrell characters

#### Difference between expected and actual behavior

should be able ot play as the species called skrell.

#### Steps to reproduce

go to character setup and try to become a skrell. You wont.

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by Mazianni** [comment]
resolved
