### ISSUE TITLE
Hairs for Unathi and Skrell not loading properly. 

### ISSUE THREAD

**Issue by GoldenSovietFox** [EscapePodNo5/EPN5-Neb#53]
#### Description of issue

Character creation, no hair for skrell nor unathi

#### Difference between expected and actual behavior

Having normal hair selection for theese specie, hair as, thier hairs, not human hairs

#### Steps to reproduce

Try to create character from theese specie

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: 1ff80207716ef6cb54db2b7f710d9883396717ec - dev - 2020-11-10
Game ID: b94-dAzw
Current map: USN Odyssey

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by Mazianni** [comment]
Skrell resolved #57 
Unathi will come later.
