### ISSUE TITLE
Skrell cannot pick any type of head-tails and are bald.

### ISSUE THREAD

**Issue by Warbidon** [EscapePodNo5/EPN5-Neb#54]
#### Description of issue
Skrell do nto have any option for head-tails.

#### Difference between expected and actual behavior
Skrell shouldnt be bald.

#### Steps to reproduce

see character menu and pick Skrell.

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by Mazianni** [comment]
Resolved #57
