### ISSUE TITLE
Sec HUD - Job Missing on HUD, Causes Red X

### ISSUE THREAD

**Issue by Stutternov** [EscapePodNo5/EPN5-Neb#56]
#### Description of issue

Missing icons on Sec-Hud; seems to be for Brig Chief and Armsman; similar to old issue with the SEA on Hestia.
![image](https://user-images.githubusercontent.com/47883419/98745613-e7b3b680-2381-11eb-99d3-eeca16ef067a.png)

#### Difference between expected and actual behavior

Should properly display job and not red X overlay

#### Steps to reproduce

Be brig chief, have glasses

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by Mazianni** [comment]
fixed #73
