### ISSUE TITLE
CMO office is not ID locked.

### ISSUE THREAD

**Issue by Warbidon** [EscapePodNo5/EPN5-Neb#58]
#### Description of issue
CMo Quarters are not ID locked

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by Mazianni** [comment]
Not a bug.
