### ISSUE TITLE
Robotics Lab Issues

### ISSUE THREAD

**Issue by Aliannera** [EscapePodNo5/EPN5-Neb#60]
#### Description of issue

The robotics lab has a few issues. For one, the vendor inside costs credits and holds a fair amount of the tools, including surgery items and the like. The toolbelt that spawns in there also starts empty, which falls into the issue again of having to spend credits to just have the tools to do your job.

Also, the lab has no materials such as metal, glass, etc. to start with the lathes and the computer in the room (robotics control console) is just a blank screen, not fully sure of it's purpose. Though if it's just for borgs and mechs, understand why that might be blank at the time.

#### Difference between expected and actual behavior

Me lab need work better so can main robo and give everyone metal arms.

#### Steps to reproduce

N/A

#### Specific information for locating

Just in the robotics lab itself.

#### Length of time in which bug has been known to occur

During the 11/12/2020 playtest.

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: 5e8a33bfb490746f5300d6c872dfee6fd55c1c5c - dev - 2020-11-11
Game ID: b96-dnT0
Current map: USN Odyssey

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by Mazianni** [comment]
Addressed.
