### ISSUE TITLE
Maptest thoughts

### ISSUE THREAD

**Issue by TheKnightofAura** [EscapePodNo5/EPN5-Neb#63]
High: 
latespawns only start with clothing.
Med:
Kitchen seems to lack a method of turning corpses into meat, IE Meathook or gibber
Low:
Botany has none of the beekeeping supply
CE can't access all maintinance, (both weapon bay access doors) (Escape pod bay 4 access, leads into Robotics, both maint doors in there lack access ) (Third deck fore port maint, only south door openable (The two that lead to botany and the back of brig. Latter should likely be secure instead) (I'm just gonna assume every single room that is job based)
CE has access to the cargo side door of commissary, but not the hallway side
Minor:
CE can't access the mining cart airlock  in coolant pump bay maint, despite being able to access both sides
CE can't' access cargo
Some safety railings that are not actually over gaps, seem arbitrary
Emergency storage is too clogged with things to get through from maintenance 
Stairwell signage is confusing as to what is upstairs, and what is up-hallways
Gnat atmos seems unpowered
No clothing/backpack locker for latespawns
Torpedo bay 1 door untagged

**Comment by Mazianni** [comment]
CE being unable to access departments via maintenance is intentional.

Same with cargo access. I'll fix the issue with disposals access. Railings are kind of scattered about for a reason. ... gnat atmos remains, annoyingly, bugged for some reason. Torpedo Bay One is out of service, so shouldn't matter too much ...?

No idea on the latespawns and their lack of backpacks, will look into that.

**Comment by TheKnightofAura** [comment]
Torpedo bay 2 is the one filled with junk, as an aside.
I can understand standard engineers not having access to everything, but they are the ones intended to fix hull breaches. if you can't get into where the breach is...

For that matter, why have maint doors, since departments besides engineering and/or electrical theoretically shouldn't be going in them
