### ISSUE TITLE
Credits Stick takes too much space in a bag.

### ISSUE THREAD

**Issue by Warbidon** [EscapePodNo5/EPN5-Neb#81]
#### Description of issue

Credits stick is a normal size item, which is a bit oversized in my opinion.
https://i.imgur.com/yRg5oTm.png
https://i.imgur.com/JEG6Dh5.png
#### Difference between expected and actual behavior
Credit-stick should fit in pockets. they dont.

#### Steps to reproduce
Get credit stick from spawning in.
fail to fit it in a pocket.

#### Specific information for locating

"credits-stick"

#### Length of time in which bug has been known to occur

since day one

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: 9cec9754ae85a749fd7908dde27f6fcb417cf868 - dev - 2021-01-30
Game ID: cam-daP5
Current map: USN Odyssey

#### Issue bingo

- [x] Issue could be reproduced at least once
-  x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by Mazianni** [comment]
Upstream issue.

**Comment by MistakeNot4892** [comment]
Fixed upstream.
