### ISSUE TITLE
Medical Storage roundstart medical supplies

### ISSUE THREAD

**Issue by Warbidon** [EscapePodNo5/EPN5-Neb#83]
#### Description of issue
Medical Supplies in Medical  seem to consist of 2 oxygen deprivation kits, 2 fire first-aid kits, 3 auto resuscitators, 1 (empty) first aid kit, a NanoMed Plus, 3 Surgical theaters (counting autopsy), 4 Sleepers and 1 scanner bed.

#### Difference between expected and actual behavior
There is a lack of a few different objects, most distinctly: cryogenics, toxin, regular(white colored) first aid kits, stethoscopes, and medical HUDs.
I prefer to have this variety of supplies in Medical so that a variety of options are available to medical staff who do not pick up stethoscopes and medical HUDs from the load out and reserve trauma and burn kits for heavier wounds, isntead using the pouches to push supplies a longer way.
Edit:we're also missing department generic supplies such as a hand labeler and crowbar/oxygen tank supplies.

#### Steps to reproduce
N/A

#### Specific information for locating

Medical Bay.

#### Length of time in which bug has been known to occur

since the beginning

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: 9cec9754ae85a749fd7908dde27f6fcb417cf868 - dev - 2021-01-30
Game ID: cam-daP5
Current map: USN Odyssey

#### Issue bingo

- [x ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- x ] Issue happened in a recent (less than 7 days ago) round
- [ x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by Kaksisilma** [comment]
Adding to that, there is also a lack of roller beds and similar.

**Comment by Warbidon** [comment]
no Sinks in either medical OR's nor in medical in general.

**Comment by Mazianni** [comment]
Cryogenics does not exist on Nebula.

**Comment by Mazianni** [comment]
Handled #100
