### ISSUE TITLE
Beakers are funny

### ISSUE THREAD

**Issue by gilvian** [EscapePodNo5/EPN5-Neb#85]
#### Description of issue

2 issues.
1. 
![image](https://user-images.githubusercontent.com/13832819/106367593-0bb0e380-6344-11eb-8cbd-6485e80cd9ee.png)
2. While filling in the acid into the circuit imprinter it just eats the beaker

Server Revision: 9cec9754ae85a749fd7908dde27f6fcb417cf868 - dev - 2021-01-30
Game ID: cam-daP5
Current map: USN Odyssey

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds

**Comment by Mazianni** [comment]
Upstream issue.

**Comment by Mazianni** [comment]
Fixed upstream.
