### ISSUE TITLE
MEDpatch pixel misplace

### ISSUE THREAD

**Issue by Warbidon** [EscapePodNo5/EPN5-Neb#86]
#### Description of issue
https://i.imgur.com/2oH0lCv.png
pixel appears when character faces left while wearing  MEDpatch.

#### Difference between expected and actual behavior
THAT WHITE PIXEL SHOULD BE GONE

#### Steps to reproduce
wear MED PATCH.
face left relative to you

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: 9cec9754ae85a749fd7908dde27f6fcb417cf868 - dev - 2021-01-30
Game ID: cam-daP5
Current map: USN Odyssey

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Fixed upstream.
