### ISSUE TITLE
Third Deck Bathroom has nonsensical amenities placement.

### ISSUE THREAD

**Issue by Warbidon** [EscapePodNo5/EPN5-Neb#87]
#### Description of issue
https://i.imgur.com/NbAJ7Z0.png
Vending machine & washing machine are facing each other and doesn't really look like it would be useful.

#### Difference between expected and actual behavior
both machines should be rotated to face towards the center of the room to make it look usable, or a change it layout.

#### Steps to reproduce
go to the bathroom. weep as the washing machine door bangs on vending machine.

#### Specific information for locating

Third Deck Bathroom

#### Length of time in which bug has been known to occur

since the beginning

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: 9cec9754ae85a749fd7908dde27f6fcb417cf868 - dev - 2021-01-30
Game ID: cam-daP5
Current map: USN Odyssey

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by Mazianni** [comment]
Washing machines only have one directional sprite. :(
