### ISSUE TITLE
circuit imprinter

### ISSUE THREAD

**Issue by gilvian** [EscapePodNo5/EPN5-Neb#88]
#### Description of issue
You can print this
![image](https://user-images.githubusercontent.com/13832819/106367903-60edf480-6346-11eb-887f-901c34d19c56.png)
on the Odyssey.

#### Client version, Server revision & Game ID
Client Version: 513
Server Revision: 9cec9754ae85a749fd7908dde27f6fcb417cf868 - dev - 2021-01-30
Game ID: cam-daP5
Current map: USN Odyssey

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds

**Comment by Mazianni** [comment]
Upstream ascent modpack issue.

**Comment by Mazianni** [comment]
Fixed upstream.
