### ISSUE TITLE
Botanics Doors are Access-Locked

### ISSUE THREAD

**Issue by Kaksisilma** [EscapePodNo5/EPN5-Neb#91]
#### Description of issue

Hydroponics should be accessible to all crewmembers.

![3](https://user-images.githubusercontent.com/54181477/106368240-f2e60500-6326-11eb-8784-0afa59d4b6d7.PNG)

#### Difference between expected and actual behavior

Assuming this is an oversight and not intended behavior.

Hydroponics currently has some sort of access-lock. As a low-security area, it should likely not have one.

#### Steps to reproduce

Try to enter Botanics as a crewmember

#### Length of time in which bug has been known to occur

Since the first round.

#### Client version, Server revision & Game ID

![rev](https://user-images.githubusercontent.com/54181477/106368180-7fdc8e80-6326-11eb-8d06-7d4153cfd9ed.PNG)

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by Mazianni** [comment]
Botany is a specific department. The Botanist has access there specifically.
