### ISSUE TITLE
Skrell have Tritonian Lungs

### ISSUE THREAD

**Issue by Kaksisilma** [EscapePodNo5/EPN5-Neb#93]
#### Description of issue

Skrell should not have Tritonian lungs. But they do.

#### Difference between expected and actual behavior

Skrell should not have Tritonian lungs. But they do. I assume it's because they both use the same type of lungs, in which case it would probably be better to rename them to "Lungs and Gills" or similar.

![5](https://user-images.githubusercontent.com/54181477/106368353-b961c980-6327-11eb-835c-2af18f2a402a.PNG)

#### Steps to reproduce

Scan or (God forbid) dissect a skrell

#### Length of time in which bug has been known to occur

Since the first round.

#### Client version, Server revision & Game ID

![rev](https://user-images.githubusercontent.com/54181477/106368373-d0a0b700-6327-11eb-985d-462268b6c551.PNG)

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by Mazianni** [comment]
handled upstream.
