### ISSUE TITLE
Full-body prosthetics are missing

### ISSUE THREAD

**Issue by Superhats** [EscapePodNo5/EPN5-Neb#99]
#### Description of issue

You can only have individual limbs as prosthetics
![image](https://user-images.githubusercontent.com/21011148/106369551-d069e100-6352-11eb-9e41-179014916cc9.png)

#### Difference between expected and actual behavior

I was expecting a "Full-body" option

#### Steps to reproduce
> Open set up
> Adjust Prosthetics
> Cry

#### Length of time in which bug has been known to occur
Tested on january 30th

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: 9cec9754ae85a749fd7908dde27f6fcb417cf868 - dev - 2021-01-30
Game ID: cam-daP5

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by quardbreak** [comment]
Nebula removed this feature a long time ago.
